config/routes.rb
Rails.application.routes.draw do
  root 'others#toppage' 
  devise_for :societies, controllers: { registrations: 'societies/registrations' }
  
  get 'societies/index'
  get 'societies/show'
  get 'societies/new'
  get 'societies/create'
  get 'societies/edit'
  get 'societies/update'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'others/toppage' => 'others#toppage' 
  get 'others/about' => 'others#about'
  get 'others/all' => 'others#all',as: 'society_all'

  get 'mypage/societymypage/:id' => 'mypage#societymypage',as:'mypage_societymypage'
  get 'mypage/usermypage/:id' => 'mypage#usermypage',as: 'mypage_usermypage'
  get 'rooms/:id' => 'rooms#show',as: 'room_show'
  post 'rooms/:id' => 'rooms#create',as: 'rooms'

  resources :rooms, :only => [:show] do
    resources :messages, :only => [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  # belongs_to :user
  belongs_to :room
  # belongs_to :society
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/society.rb
class Society < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :messages, dependent: :destroy
  # has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  # has_many :entries, dependent: :destroy
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        case resource
        when User
            mypage_usermypage_path(current_user.id)
        when Society
            mypage_societymypage_path(current_society.id)
        end
    end
  
    def after_sign_out_path_for(resource)
        others_toppage_path
    end 
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @message = Message.new(message_params)
    #メッセージがuserによるものだったらis_user=true, shopによるものだったらis_user=false
    if user_signed_in?
      @message.sender_id = current_user.id
      @message.is_user = true
    elsif society_signed_in?
      @message.sender_id = current_society.id
      @message.is_user = false
    end
    @message.room_id = @room.id
    if @message.save
      redirect_to room_url(@room)
    else
      redirect_to room_url(@room)
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    if user_signed_in?
      @societies = Society.all
      rooms = current_user.rooms
      #自分が入ってるroomの相手のidを格納する
      @society_ids = []
      rooms.each do |r|
        @society_ids << r.society_id
      end
    
    elsif society_signed_in?
      @users = User.all
      rooms = current_shop.rooms
      #自分が入ってるroomの相手のidを格納する
      @user_ids = []
      rooms.each do |r|
        @user_ids << r.user_id
      end
    end
  end
  def usermypage
    @user = User.find(params[:id])
  end
  def societymypage
    @society = Society.find(params[:id])

    if society_signed_in?
      @users = []
      @entries = Entry.where(society_id: current_society.id)
      @entries.each do |entry|
        @user = User.find(entry.user_id)
        @users.push(@user)
      end
    end
    end
  end
 

app/controllers/others_controller.rb
class OthersController < ApplicationController

    # def new
    #     @society = Society.new
    #     @user = User.new
    # end

    # def index
    #     @societies = Society.all
    #     @users = User.all
    # end

    # def show
    #     @society = Society.find(params[:id])
    #     @user = User.find(params[:id])
    # end

    # def edit
    #     @society = Society.find(params[:id])
    #     @user = User.find(params[:id])
    # end

    # def link
    # end
    def all
        @societies = Society.all
    end

    def toppage
    end

    private

    def user_params
      params.require(:society).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    @room = Room.find(params[:id]) #ルーム情報の取得
    @message = Message.new #新規メッセージ投稿
    @messages = @room.messages #このルームのメッセージを全て取得
    @entry = Entry.find_by(room_id: @room.id)
    @society = Society.find(@entry.society_id)
    @user = User.find(@entry.user_id)
  end

  def create
    
    if user_signed_in?
      #userがログインしてたらuser_idを, shopがログインしてたらshop_idを@roomにいれる
      @search_entry = Entry.find_by(user_id: current_user.id,society_id: params[:id])
      if @search_entry.nil?
      @room = Room.create
      @entry = Entry.create(user_id: current_user.id, society_id: params[:id],room_id: @room.id)
      else
        @room = Room.find(@search_entry.room_id)
      end
    elsif society_signed_in?
      @search_entry = Entry.find_by(user_id: params[:id],society_id: current_society.id)
      @room = Room.find(@search_entry.room_id)
    else
      redirect_to "/"
    end
      redirect_to :action => "show", :id => @room.id
  
  end
  
  private
  # def room_user_params
  #   params.require(:room).permit(:user_id)
  # end

end

app/controllers/society_controller.rb
class SocietyController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/society_helper.rb
module SocietyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mypage/message.html.erb
<h1>チャットサンプル</h1>
<!--Userでログインしてたら-->
<% if user_signed_in? %>
  ~<%= current_user.name %>がログインしてます~
  <%= link_to "ログアウト", destroy_user_session_path ,:method => :delete %>
  <br>
  <h2>ショップ一覧</h2>
  <br>

  <% @societies.each do |society| %>
    <%= society.name %>
    <!-- もしチャットルームがあったらそのチャットページへ。なければ新たなチャットルームを作成 -->
    <% if @society_ids.include?(society.id) %>
      <br>
      <%= link_to "チャットへ", room_path(current_user.rooms.find_by(society_id: society.id)) %><br>
    <% else %>
      <%= form_for Room.new do |f| %>
        <%= f.hidden_field :society_id, :value => society.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
  <% end %>
  
<!--Shopでログインしてたら-->
<% elsif society_signed_in? %>
  <h2>ユーザー一覧</h2>
  <br>
  ~<%= current_society.name %>がログインしてます~
  <%= link_to "ログアウト", destroy_society_session_path ,:method => :delete %>
  <br>
  <% @users.each do |user| %>
    <%= user.name %>
    <!-- もしチャットルームがあったらそのチャットページへ。なければ新たなチャットルームを作成 -->
    <% if @user_ids.include?(user.id) %>
      <br>
      <%= link_to "チャットへ", room_path(current_shop.rooms.find_by(user_id: user.id)) %><br>
    <% else %>
      <%= form_for Room.new do |f| %>
        <%= f.hidden_field :user_id, :value => user.id %>
        <%= f.submit %>
      <% end %>
    <% end %>

  <% end %>

<!--ログインしてなかったら-->
<% else %>
  <h3>ユーザー</h3>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
  <h3>ショップ</h3>
  <%= link_to "ログイン", new_society_session_path %>
  <%= link_to "新規登録", new_society_registration_path %>
<% end %>

app/views/mypage/societymypage.html.erb
<h1><%=@society.name%>さんのマイページ</h1>
<%= link_to '登録情報修正', societies_edit_path %>
<%= link_to 'ログアウト', destroy_society_session_path, method: :delete %>
<%= link_to "メッセージ", rooms_path(@society.id),method: :post %>

<% if society_signed_in?%>
<div>過去のDMリスト</div>
  <% @users.each do |user|%>
  <%= link_to rooms_path(user.id) , method: :post do%>
  <div><%= user.name %>さんとのDM</div>
    <% end %>
  <% end %>
<% end %>

app/views/mypage/usermypage.html.erb
<h1><%= @user.name %>さんのマイページ</h1>
<%= link_to '登録情報修正', users_edit_path %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to '楽団一覧へ',society_all_path%>

app/views/others/about.html.erb
このサイトについて

app/views/others/all.html.erb
<div class="societies-container">
  <% @societies.each do |t| %>
    <div class="society" style='border:2px solid black;margin:20px;'>
      <%= t.name %>
      <div>
      <%= link_to mypage_societymypage_path(t.id) do %>
        この楽団のマイページをみる
      <% end %>
       </div>
    </div>
  <% end %>
</div>

app/views/others/toppage.html.erb
<%= stylesheet_link_tag 'toppage', :media => "all" %>
<div class="center">Musicappへようこそ！</div>
<p>『あなたが必要とする』or『あなたを必要としている』オーケストラやアマチュア奏者をお探しします！</p><br />